# arxivの学問領域の指定
subject: 'cat:q-bio.*'

# 検索キーワード
keywords:
       hypoxia: 2
       hypoxic: 2
       hypoxia room: 3
       hypoxic room: 3
       exercise: 1
       SpO2: 2
       HRV: 1
       Heart rate: 1
       Heart rate valiability: 1
       Heart: 1
       

# 通知の閾値
score_threshold: 0
